# Generated by Django 2.2.6 on 2019-10-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zillaname',
        ),
    ]
