# Generated by Django 2.2.6 on 2019-12-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0006_auto_20191206_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.Profile'),
        ),
    ]
