# Generated by Django 2.2.6 on 2019-12-09 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimerepost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('district', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_instant', models.BooleanField(default=True)),
                ('refer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refer_user', to='authenticate.Profile')),
                ('take_under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_under', to='authenticate.Profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
