# Generated by Django 2.2.6 on 2019-11-27 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerepost',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crimerepost',
            name='is_instant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crimerepost',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
