# Generated by Django 2.2.6 on 2019-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerepost',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
