# Generated by Django 2.2.6 on 2019-12-06 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cr', '0002_auto_20191127_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerepost',
            name='refer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crimerepost',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crimerepost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
