# Generated by Django 2.2.6 on 2019-12-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0003_auto_20191206_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimerepost',
            name='refer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refer_user', to='authenticate.Profile'),
        ),
    ]
