# Generated by Django 2.2.6 on 2019-10-28 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20191017_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='type_of',
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
